### ISSUE TITLE
Deployment not working 

### ISSUE THREAD

**Issue by tiberain** [Azure/Moodle#100]
Hey,

So up until yesterday I've been creating and deleting a deployment of the Fully configurable deployment. Sense yesterday evening I've been getting different error for the deployment some have been conflicts and other have been network.
![screenshot_47](https://user-images.githubusercontent.com/2485554/39860330-d14062e6-5434-11e8-9c3b-a80ed2d51c88.png)

**Comment by rgardler** [comment]
@hosungs please take a look at this. Looks like a problem introduced by the Tika work.

**Comment by hosungsmsft** [comment]
Thanks @tiberain for letting us know. @rgardler -- No, Tika check-in is just fine. It passed the full CI. See https://travis-ci.org/Azure/Moodle/builds/376897721 .

Turns out that our tshirt-sizing -> master merge was flawed for GUI buttons (didn't update the base URLs for the different branch). I'll commit a fix very soon, which should auto-close this issue.
