### ISSUE TITLE
VSTS Send file over SSH

### ISSUE THREAD

**Issue by tiberain** [Azure/Moodle#109]
Hey,

I'm wondering if anyone is else is trying to use TFS as a way to run build and releases of  plugins and blocks.
I have a simple block that was developed before and we know it works, my problems is that I can't seem to get it to deploy at the root level on the Linux box, it seems to put all the files and folders into the user directory.
User dir:
/home/azureadmin: 
I need to places the blocks within:
/moodle/html/moodle/blocks/

![screenshot_48](https://user-images.githubusercontent.com/2485554/40113710-44bf10a6-5902-11e8-9d9c-eaff6978d424.png)

I've tired:
~moodle/html/moodle/blocks/
/moodle/html/moodle/blocks/
../../moodle/html/moodle/blocks/
and loads more like this and either it fails or just adds the code to the users root

**Comment by hosungsmsft** [comment]
It looks like an interesting use case of VSTS, and I'm not sure if anyone has experiences with VSTS sftp/scp deployment (I myself don't). But looking at the documentations (like [this](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/copy-files-over-ssh?view=vsts) and [this](https://blogs.msdn.microsoft.com/devops/2016/08/18/copy-files-over-ssh-during-continuous-integration-and-deployment/)), it looks like absolute paths and arbitrary folders should be supported. If that's not the case, I'd suggest to contact the VSTS team for their support (as described [here](https://blogs.msdn.microsoft.com/devops/2016/08/18/copy-files-over-ssh-during-continuous-integration-and-deployment/)).

One thing I wanted to ask is if you set the `htmlLocalCopySwitch` to true when you deploy the templates. If so, then you must run the `/usr/local/bin/update_last_modified_time_update.moodle_on_azure.sh` script on the controller machine, in order to initiate synchronization of the changes in your `/moodle/html/moodle` to all the web frontend machines. It appears that VSTS also supports running such a remote command as a deploy step. Just FYI. Thanks.

**Comment by rgardler** [comment]
@tiberian can you please describe exactly what you are doing. That is which machine do you have VSTS connecting to, what is the configuration script etc.

**Comment by tiberain** [comment]
Hey,

So what we are doing is helping a company set up moodle. They will manage there moodle themselves. Now here is where the VSTS part comes in they have custom blocks and plugins they created and developed. What we are planning on doing is having a minimum deployment (dev environment) beside the possible maximum deployment (live environment). Are plan is to set them up with VSTS for them to use as source control and then a deployment cycle so the release first goes to the dev environment for them to test it works then once there happy and confirm the update it goes to the live environment.
So there is two way to do SSH within VSTS we are not using the script way yet we are using what is in that script from above.

**Comment by rgardler** [comment]
OK, but to debug why this isn't working we need to understand what you are doing. You've explained what you want to achieve, but not what you are actually doing.

If I understand correctly you believe you designed a solution that will satisfy the customers needs, but that it doesn't work.

You've said "I can't seem to get it to deploy at the root level on the Linux box, " but you haven't said what "the linux box" is. Are you talking about the NFS, Gluster FS configurations, or perhaps you are trying to write directly to the disk on the front-end VMs.

To be clear, I don't think any of us are VSTS experts, but once we have enough information we can likely find someone to take a look at the problem.

**Comment by tiberain** [comment]
Hey @rgardler,

So I'm trying place the code on in the controller VM. I'm using the Fully configurable version but, left everything in the default.
The problem is I can't seem to get it not to deploy the code on the home directory of the user.
It need to be deployed in the root

**Comment by tiberain** [comment]
hey @rgardler. @hosungsmsft,

So in #144 I've stated that I've had trouble scene Moodle installed has been fixed that is more related to this.
I was able to get VSTS to work. But I was unable to run the script /usr/local/bin/update_last_modified_time_update.moodle_on_azure.sh 

Do you have a correct way for someone to add blocks. To my knowlege you need to add them to the blocks folder and then run the script. But so far I havn't been able to get this to work.

Thanks,
For your help in advance.

**Comment by hosungsmsft** [comment]
#144 has nothing to do with this VSTS ssh file transfer issue. I can't know what kind of issues you are encountering with running the script, but I assume it's a basic Unix/Linux command like usage skill. Since I have no idea how you are accessing the Linux VM or how you are running the script on it, we can't really help you, and I don't think this way of going back and forth on this GitHub messages is not a good way to troubleshoot this. I strongly recommend that you set up some online remote screen sharing meeting with me to go through all this more efficiently.
