### ISSUE TITLE
Need Guidance about Moodle on Azure (Azure Calculator & Configuration)

### ISSUE THREAD

**Issue by AdityaHartono** [Azure/Moodle#117]
Hi Nima

My company has an opportunity to handle Project Moodle on Azure for Universities, and for this project i have 2 (Two) Scenario deployment :
1). 300 Concurrent users **without High Availability**.
2). 2000 concurrent users **with High Availibility**.

300 concurrent users without HA :
concurrent users when peak : 300 users
concurrent users when normal : 50 users

2000 concurrent users with HA :
concurrent users when peak : 2000 users
concurrent users when normal : 300 Users

With scenario above i want to know about the specification hardware should i configure for create estimated cost, because i need to give the estimation cost to customer.

and is it possible to help me create Moodle github template with 2 scenario above?

Thanks.

**Aditya Hartono.**

**Comment by rgardler** [comment]
Take a look at the repo Readme which provides some initial guidance on configurations ideal for your suggestion above. Note that these are only broad guidelines, it's not really possible to provide specific guidance without a full understanding of the use case, but the Readme gives a good starting point.

I recommend you start with those configs, and use our load testing scripts to validate your configuration. If you have questions about a specific configuration option we'd be happy to try to help.

**Comment by AdityaHartono** [comment]
Hi @nimojg-microsoft @hosungsmsft @rgardler  currently i'm on testing deploy the moodle with minimal deployment & large size deployment templates.

i successfully deploy on azure.

i have questions : 
1. What is default user & password of admin moodle on the templates?
2. Why when RDP on VM moodle, display of desktop not normal (attached)  
![rdp to moodle](https://user-images.githubusercontent.com/39509712/41204703-62530428-6d12-11e8-8c80-287019d1163f.PNG)

**Comment by rgardler** [comment]
There are various pieces of information that are auto generated for you. You can find documentation on how to retrieve them in https://github.com/Azure/Moodle/blob/master/docs/Get-Install-Data.md

**Comment by hosungsmsft** [comment]
@AdityaHartono -- Regarding your question 1, @rgardler's answer would be probably best, though you might prefer finding those out on the Azure Portal. Doing so is a bit tricky and hard to explain, because you need to go to the resource group which you created and where you deployed the templates, then click the "Deployments" menu item in the resource group blade, then click either the "Microsoft.Deployment" deployment (if you deployed your templates from the Portal) or the "azuredeploy" deployment (if you deployed your templates from the CLI), then finally click the "Outputs" menu item, where you should see all the needed information.

Regarding your question 2, I don't even know how you could be able to RDP to the deployed "Linux" VM (which we don't install/configure any Linux-RDP support at all, so RDP shouldn't be available in the first place). If you configured RDP on the Linux VM using something like xrdp (which I suppose is the case, from the screenshot), then please consult the relevant documentation on how to set up/use xrdp correctly. Our templates don't support xrdp by default. The only currently supported mechanism to get access to the deployed VMs is using ssh with a program like Putty (on Windows) or the Linux ssh command.

**Comment by AdityaHartono** [comment]
Hi @Hosung Song & @rgardler 
Thank you very much! After reading your explanation, i'm successfully login to Admin Moodle.
Actually i'm newbie in moodle & have no experience on linux, so sorry if my question looks stupid :)

**Comment by hosungsmsft** [comment]
Thanks @AdityaHartono for letting us know. There's no stupid question, so don't worry and just help us help you better by explaining your situations clearly.
