### ISSUE TITLE
Rename Site URL

### ISSUE THREAD

**Issue by jimbojonesirl** [Azure/Moodle#157]
Hi,

Is it possible to change the site url e.g https://test.moodle.domain.com to https://live.moodle.domain.com? In our on premises deployments it is a simple rename in the Moodle config.php and update DNS records. Is there any further changes needed for this to work with this deployment?

Thanks,

**Comment by hosungsmsft** [comment]
Yes, that's right. Just update your Moodle deployment's `config.php` file with your new domain name (for `$CFG->wwwroot`, need to do this on your controller machine), update your DNS record (so that your `live.moodle.domain.com`'s CNAME points to the load balancer's FQDN--e.g., `lb-pupip-xyz123.somewhere.cloudapp.azure.com`), then there might be one last step needed, depending on one of your initial deployment options. If you left the `htmlLocalCopySwitch` option as is (which is `true` by default), then you need to log on to your controller machine, and run the shell script `/usr/local/bin/update__last_modified_time.moodle_on_azure.sh`) so that your change in the `config.php` is replicated to all web server instances. If you set the `htmlLocalCopySwitch` option to `false` at your deployment time (which I think is unlikely, unless you have had some very specific requirement), then this last step is not needed. Let me know if this doesn't work, or close this issue after you confirm it's working. Thanks.

**Comment by rgardler** [comment]
Closing as I am assuming the previous answer was sufficient. If not feel free to reopen.
