### ISSUE TITLE
NetApp vs. Gluster/NFS HA for Moodle files?

### ISSUE THREAD

**Issue by kamcgreg** [Azure/Moodle#168]
Would NetApp in Azure be a good alternative to Gluster or NFS HA for Moodle files?

**Comment by rgardler** [comment]
Yes. We did load testing with NetApp it performed very well. It was slightly less performant, but still passed out most stringent use cases. If course as SaaS is one less thing to manage.

Although undocumented the configuration you need is actually in the code today. It's undocumented because at the time we wrote these templates NetApp was in preview and we have not verified that the code works with the GA service. 

If you try it we'd love your feedback.

**Comment by rgardler** [comment]
Close due to inactivity

**Comment by Akshat-Kesarwani** [comment]
@rgardler I am about to do a deployment of Moodle and plan to use NetApp for Moodle files. I will definitely provide my experience and configuration done for this. But also wanted to check if there are updates on this?

**Comment by UmakanthOS** [comment]
@Akshat-Kesarwani We had recently prioritized Azure Files and general template updates and while Azure NetApp Files was in consideration, not much work has happened here yet.

**Comment by ChrisLopezUK** [comment]
Should be good to use byo-nfs if you set up your NetApp files in advance.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
